---
version: "3.9"
services:
  web:
    image: idiosyncratic/amphp-webapp
    restart: always
    ports:
    - '80:80'
    volumes:
    - '.:/app'
    - './docker/php.ini-development://usr/local/etc/php/php.ini'
    environment:
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_ENABLE_CLI: 1
      PHP_OPCACHE_INTERNED_STRINGS_BUFFER: 64
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 100000
      PHP_OPCACHE_MEMORY_CONSUMPTION: 512
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_OPCACHE_FILE_CACHE: /tmp/phpopcache
